### ISSUE TITLE
ModuleNotFoundError: No module named 'attrmap'

### ISSUE THREAD

**Issue by Eddylusamaki** [shandley/hecatomb#101]
Dear Shandy,

I install Hecatomb on MacOS system following conda procedure.
Running `hecatomb install --threads 8` bring this error: 

> ModuleNotFoundError: No module named 'attrmap'

I solved the issue by installing attrmap on my hecatomb conda env with: `conda install -c conda-forge attrmap --yes`

I think attrmap is not default install on Macos system, maybe add it on conda dependency ? :)

Have a good,
Best regard,

**Comment by beardymcjohnface** [comment]
Hi,
Thanks for posting. I believe this module was removed in the current release, and it wont be in the next one.
