### ISSUE TITLE
additional script to merge new data with old at seqtable_merge.R level

### ISSUE THREAD

**Issue by mihinduk** [shandley/hecatomb#20]
If we had a script that would allow us to merge new results with a previous seq table, this could make processing projects with additional rounds of sequencing (or combining several projects related to the same disease or body site) more efficient.

**Comment by mihinduk** [comment]
Might also speed this process up to convert the script from R to python

**Comment by shandley** [comment]
Agree. This would also be useful for combining projects. I have been thinking about this a lot lately.

In general I am supportive of converting some of the R code to Python for the speed gains. Changing this to an enhancement. I am not a good enough python programmer to do that part, but I do plan on working on this in R.

**Comment by beardymcjohnface** [comment]
Cleaning up old issues. This should be addressed with both the format of the bigtable (can simply concatenate), and the combine script `hecatomb combine ...`
