### ISSUE TITLE
WorkflowError in line 122 of 01_contaminant_removal_hosts.smk: Resources function did not return int.

### ISSUE THREAD

**Issue by Leran10** [shandley/hecatomb#25]

**Comment by linsalrob** [comment]
Can you please test adding 

```
--default-resources cpus=1 mem_mb=2000
```

to your command line? I think it is because there are no default resources defined. An alternate way to do that is to set up the [profile](https://github.com/shandley/hecatomb/blob/master/INSTALLATION.md#slurm-profile) that defines the values.
