### ISSUE TITLE
For NextSeq samples, maximum HTCF memory insufficient for merge seqtable step in R

### ISSUE THREAD

**Issue by mihinduk** [shandley/hecatomb#28]
I have tried with the max memory (#SBATCH --mem=250G) and 42 samples, but it ends in an out of memory error:
Failed, Run time 04:46:02, OUT_OF_MEMORY

/var/lib/slurm-llnl/slurmd/job28663469/slurm_script: line 13: 12927 Killed                  Rscript /scratch/sahlab/Jeffrey_NextSeq_IBD_VLP/seqtable_merge.R
slurmstepd: error: Detected 1 oom-kill event(s) in step 28663469.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler. 

All samples make it through this step:
Parsed with column specification:
cols(
  sequence = col_character(),
  `N646_I8216_32668_Jeffrey_Sup_10_NEBNext-Index-16C_CCGTCCGC_S11` = col_double()
)

and then the error occurs.

We may have to convert to python or somehow decrease memory usage for this script if we want to process NextSeq data.

Kathie

**Comment by shandley** [comment]
This will be an issue for large data files. Will need to come up with a more optimal solution for tissue samples. Closing for now but can readdress when we have the newer version of the workflow completed.
