### ISSUE TITLE
megahit -> flye reformatting

### ISSUE THREAD

**Issue by mihinduk** [shandley/hecatomb#29]
Hi Scott,
This is the current reformat command between megahit and flye:
```
reformat.sh in={output.rename} out={output.size} \
        ml={config[MINLENGTH]} \
        ow=t \
        -Xmx{config[System][Memory]}g;
```

If you try to run flye with the same MINLENGTH as megahit, you may fail immediately because of duplicate names.  This can be solved by adding this to the reformat command:
`uniquenames=t `

Kathie

**Comment by shandley** [comment]
I believe this has been fixed in the newest version. If it's still an issue we can revisit.
