### ISSUE TITLE
pipeline requires higher version of conda which has --conda-frontend parameter

### ISSUE THREAD

**Issue by Leran10** [shandley/hecatomb#36]
Hi,

When I firstly ran hecatomb it failed at the beginning because it cannot find the --conda-frontend parameter that the pipeline required. 

This issue could go away after I updated my conda version to conda 4.10.3.

Thanks!
Leran

**Comment by beardymcjohnface** [comment]
That's good to know. The GitHub install is only intended for development purposes and we want to steer users away from manually installing from GitHub.
