### ISSUE TITLE
kill switch

### ISSUE THREAD

**Issue by mihinduk** [shandley/hecatomb#39]
Hi Mike,

Can you add to the documentation how to kill hecatomb?  I killed the tmux session, but it is my understanding that to kill snakemake, I have to <control> A each running process.

Kathie

**Comment by beardymcjohnface** [comment]
Hi Kathy,
When the pipeline is run as a local job (not using `--profile`), killing the session _will_ kill everything. When running with `--profile` any jobs submitted to the scheduler will continue running and you would have to kill them manually or just wait for them to finish.
