### ISSUE TITLE
updating hecatomb

### ISSUE THREAD

**Issue by mihinduk** [shandley/hecatomb#40]
Hi Mike,

Can you add to the documentation how to update hecatomb?  Do we have to reinstall when there is an update?  Will hecatomb alert us to major updates?

Thank you,
Kathie

**Comment by beardymcjohnface** [comment]
Hi Kathie,
I'll be pushing the next build to bioconda, so you will be able to update it like so:
`conda update -c bioconda hecatomb`
The pipeline wont currently check for more recent versions.
