### ISSUE TITLE
Hecatomb v1.0.0.beta.2 crash

### ISSUE THREAD

**Issue by mihinduk** [shandley/hecatomb#43]
Hi Mike,

I only got **86%** of the way through this time:

[Thu Nov  4 02:02:55 2021]
Finished job 1885.
1894 of 2200 steps (86%) done
Exiting because a job execution failed. Look above for error message

    FATAL: Hecatomb encountered an error.
           Dumping all error logs to "hecatomb.errorLogs.txt"Complete log: /scratch/sahlab/RC2_IBD_virome/allt_results/.snakemake/log/2021-11-03T210405.313772.snakemake.log

Complete log: /scratch/sahlab/RC2_IBD_virome/allt_results/.snakemake/log/2021-11-03T210405.313772.snakemake.log:
rule concatentate_contig_count_tables:
**benchmark: hecatomb_out/BENCHMARKS/concatentate_contig_count_tables.txt**
s	h:m:s	max_rss	max_vms	max_uss	max_pss	io_in	io_out	mean_load	cpu_time
37.3387	0:00:37	5.26	20.88	1.20	1.48	172.50	172.50	0.68	0.25

cat hecatomb_out/PROCESSING/ASSEMBLY/CONTIG_DICTIONARY/MAPPING/...
sed -i '1i sample_id	contig_id	length	reads	RPKM	FPKM	TPM	avg_fold_cov	contig_GC	cov_perc	cov_bases	median_fold_cov' hecatomb_out/PROCESSING/ASSEMBLY/CONTIG_DICTIONARY/MAPPING/contig_count_table.tsv;         } 2> hecatomb_out/STDERR/concatentate_contig_count_tables.log
        **rm hecatomb_out/STDERR/concatentate_contig_count_tables.log**

************************************************************************************************
    benchmark: hecatomb_out/BENCHMARKS/mmseqs_contig_annotation.txt
    threads: 32
    resources: mem_mb=64000, time=1440, jobs=100

        {
        mmseqs createdb hecatomb_out/PROCESSING/ASSEMBLY/CONTIG_DICTIONARY/FLYE/assembly.fasta hecatomb_out/PROCESSING/ASSEMBLY/CONTIG_DICTIONARY/FLYE/queryDB --dbtype 2;
        mmseqs search hecatomb_out/PROCESSING/ASSEMBLY/CONTIG_DICTIONARY/FLYE/queryDB /home/mihindu/miniconda3/envs/hecatomb/snakemake/workflow/../../databases/nt/virus_primary_nt/sequenceDB hecatomb_out/PROCESSING/ASSEMBLY/CONTIG_DICTIONARY/FLYE/results/result hecatomb_out/PROCESSING/ASSEMBLY/CONTIG_DICTIONARY/FLYE/mmseqs_nt_tmp             --start-sens 2 -s 7 --sens-steps 3 --min-length 90 -e 1e-5             --search-type 3 ; } &> hecatomb_out/STDERR/mmseqs_contig_annotation.log
        rm hecatomb_out/STDERR/mmseqs_contig_annotation.log

Error submitting jobscript (exit code 1):

Job failed, going on with independent jobs.

[Thu Nov  4 00:27:44 2021]
rule coverage_calculations:

**1.  Checked the presence of the db:**
ls /home/mihindu/miniconda3/envs/hecatomb/snakemake/workflow/../../databases/nt/virus_primary_nt/

sequenceDB  sequenceDB.dbtype  sequenceDB_h  sequenceDB_h.dbtype  sequenceDB_h.index  sequenceDB.index  sequenceDB.lookup  sequenceDB.source

**2.  Checking Flye output:**
ls /scratch/sahlab/RC2_IBD_virome/allt_results/hecatomb_out/PROCESSING/ASSEMBLY/CONTIG_DICTIONARY/FLYE
00-assembly  22-plasmids   40-polishing    assembly_graph.gfa  assembly_info.txt        flye.log
20-repeat    30-contigger  assembly.fasta  assembly_graph.gv   contig_dictionary.stats  params.json

**NOTE: no results or mmseqs_nt_tmp  folders**
***************************************************************************************************************

Unfortunately, the crash log is empty:
wc -l hecatomb.crashreport.log
0 hecatomb.crashreport.log

**Comment by beardymcjohnface** [comment]
The crash logs are cleaned up after each rule finishes (but for some snakemake reason they remain as empty files). Are you sure 'concatentate_contig_count_tables' was the one that failed? I would check the scheduler logs as well in logs/ (if you're using the example profile).

**Comment by beardymcjohnface** [comment]
There is a new release of Hecatomb which may or may not address this issue. Please reopen if this problem is still occurring.
