### ISSUE TITLE
Run Offline

### ISSUE THREAD

**Issue by gbouras13** [shandley/hecatomb#47]
Hi,

The cluster I am trying to run hecatomb on blocks all internet access to compute nodes, which is very frustrating. 

It looks like a couple of rules in 00_functions.smk rely on Snakemake wrappers - for bam_index and fasta_index rules and so require internet access. 

The entire log file I get when I run hecatomb on the compute node is:

Config file /hpcfs/users/a1667917/myconda/envs/hecatomb/snakemake/workflow/../config/config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
WorkflowError:
Failed to open source file https://github.com/snakemake/snakemake-wrappers/raw/0.77.0/bio/samtools/index/environment.yaml
ConnectTimeout: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /snakemake/snakemake-wrappers/raw/0.77.0/bio/samtools/index/environment.yaml (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f65c0836c80>, 'Connection to github.com timed out. (connect timeout=None)'))

I commented out the wrapper for the 2 rules and hecatomb ran fine other than the very final indexing step (I then uncommented and ran the indexing steps on the login node - which worked to complete the pipeline just fine).

Therefore, as far as I can tell, this is the only section of hecatomb that requires online access - perhaps you could implement an option to run offline only? 

I tried to manually change the snakemake rule to something like samtools index {input} but that didn't work.

George

**Comment by beardymcjohnface** [comment]
I George,
I did not foresee this being an issue. I'll roll back the use of wrappers for the next release. We already create a Samtools env so it's no big deal.

**Comment by beardymcjohnface** [comment]
I've created a new release with this fix and it should be available by tomorrow from bioconda. You should be able to activate your hecatomb environment and run `mamba update -c bioconda hecatomb`
