### ISSUE TITLE
hecatomb install  giving error

### ISSUE THREAD

**Issue by Vikash84** [shandley/hecatomb#52]
hecatomb install
Checking and downloading database files
Running snakemake command:
snakemake -j 32 --use-conda --conda-frontend mamba --rerun-incomplete --printshellcmds --nolock --show-failed-logs --conda-prefix /home/vsingh/miniconda3/envs/hecatomb/snakemake/workflow/conda  -s /home/vsingh/miniconda3/envs/hecatomb/snakemake/workflow/DownloadDB.smk -C Output=hecatomb_out
Config file /home/vsingh/miniconda3/envs/hecatomb/snakemake/workflow/../config/config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
/usr/bin/bash: line 10: __conda_exe: command not found
Traceback (most recent call last):
  File "/home/vsingh/miniconda3/envs/hecatomb/lib/python3.9/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/home/vsingh/miniconda3/envs/hecatomb/lib/python3.9/site-packages/snakemake/workflow.py", line 973, in execute
    self.scheduler = JobScheduler(
  File "/home/vsingh/miniconda3/envs/hecatomb/lib/python3.9/site-packages/snakemake/scheduler.py", line 348, in __init__
    self._executor = CPUExecutor(
  File "/home/vsingh/miniconda3/envs/hecatomb/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 453, in __init__
    self.exec_job += self.get_additional_args()
  File "/home/vsingh/miniconda3/envs/hecatomb/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 298, in get_additional_args
    if self.workflow.conda_base_path and self.assume_shared_fs:
  File "/home/vsingh/miniconda3/envs/hecatomb/lib/python3.9/site-packages/snakemake/workflow.py", line 276, in conda_base_path
    return Conda().prefix_path
  File "/home/vsingh/miniconda3/envs/hecatomb/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 439, in __init__
    shell.check_output(self._get_cmd("conda info --json"))
  File "/home/vsingh/miniconda3/envs/hecatomb/lib/python3.9/site-packages/snakemake/shell.py", line 63, in check_output
    return sp.check_output(cmd, shell=True, executable=executable, **kwargs)
  File "/home/vsingh/miniconda3/envs/hecatomb/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/vsingh/miniconda3/envs/hecatomb/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'conda info --json' returned non-zero exit status 127.

**Comment by beardymcjohnface** [comment]
Hi, it looks like it cant run conda/mamba. How did you install Hecatomb?

**Comment by Vikash84** [comment]
I install using conda as suggested

conda create -n hecatomb -c conda-forge -c bioconda hecatomb

and hecatomb -h is working


██╗  ██╗███████╗ ██████╗ █████╗ ████████╗ ██████╗ ███╗   ███╗██████╗ 
██║  ██║██╔════╝██╔════╝██╔══██╗╚══██╔══╝██╔═══██╗████╗ ████║██╔══██╗
███████║█████╗  ██║     ███████║   ██║   ██║   ██║██╔████╔██║██████╔╝
██╔══██║██╔══╝  ██║     ██╔══██║   ██║   ██║   ██║██║╚██╔╝██║██╔══██╗
██║  ██║███████╗╚██████╗██║  ██║   ██║   ╚██████╔╝██║ ╚═╝ ██║██████╔╝
╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝     ╚═╝╚═════╝ 

Version v1.0.0.beta.3

Commands:
    install     Download and install the databases (only have to do once)
    run         Run the Hecatomb pipeline
    config      Copy the default configfile to the current directory
                (for use with --configfile)
    listHosts   List the available host genomes for contaminant removal
    addHost     Process and add a new host genome for contaminant removal

positional arguments:
  {install,run,config,listHosts,addHost}

optional arguments:
  -h, --help            show this help message and exit
  --reads READS         Either directory containing seq data, or TSV specifying samples and seq files. See https://hecatomb.readthedocs.io/en/latest/usage/ for more info.
  --configfile CONFIGFILE
                        Specify your own config file. First copy the template with "hecatomb config".
  --test                Use the test dataset (ignores --reads)
  --skipAssembly        Don't perform an assembly
  --report              Generate a run report
  --results RESULTS     Directory to write the output files
  --host HOST           Host name for contaminant removal
  --hostfa HOSTFA       Host reference (for addHost command only)
  --profile PROFILE     Snakemake profile for use on cluster
  --threads THREADS     Number of threads to use (ignored if using --profile)
  --fast                Use faster but less sensitive settings for MMSeqs searches
  --snake SNAKE         Pas

**Comment by linsalrob** [comment]
Hi Vikash

It looks like you have the same issue [described here for conda](https://stackoverflow.com/questions/69001097/conda-4-10-3-and-snakemake-5-conda-exe-problem?answertab=active#tab-top), however we have not run into that. I suspect is it is a specific conda/snakemake version compatibility problem.

Can you please add this after the conda stanzas (i.e., after the "# <<< conda initialize <<<") in `~/.bashrc`:

```
# Make these functions available to scripts.
export -f conda
export -f __conda_activate
export -f __conda_reactivate
export -f __conda_exe
```

You will need to log out and log back in again to make the change permanent.

Once you have done that, please try hecatomb again, and please let us know if this fixes the problem in case others run into the same issue. As always, its impossible for us to debug without experiencing the problem!

Rob

**Comment by Vikash84** [comment]
Hi Rob,

Thanks for your prompt reply and run test run was completed successfully.

Thanks
Vikash
