### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mihinduk** [shandley/hecatomb#58]
Hi,

For the documentation, can you add a link under each output files to a table that defines each column?
Ex: bigtable.tsv
seqID	UID for each representative sequence

This would make the tool more easily accessible, but not clutter the doc.

Thank you,
Kathie

**Comment by beardymcjohnface** [comment]
Hi Kathie,
I have updates ready to go for the bigtable and contigseqtable which I'll push soon. Do you think any of the other files need a table as well?

**Comment by beardymcjohnface** [comment]
I've made a few updates to the documentation. Please reopen or open a new issue if you have any ideas for future updates!
