### ISSUE TITLE
Error executing PRIMARY_NT_reformat

### ISSUE THREAD

**Issue by shandley** [shandley/hecatomb#60]
Cluster error:

/bin/bash: line 10: 18485 Illegal instruction     (core dumped) mmseqs filterdb hecatomb_out/RESULTS/MMSEQS_NT_PRIMARY/results/result hecatomb_out/RESULTS/MMSEQS_NT_PRIMARY/results/firsthit --extract-lines 1

Log file error report (same as above):

/bin/bash: line 10: 18485 Illegal instruction     (core dumped) mmseqs filterdb hecatomb_out/RESULTS/MMSEQS_NT_PRIMARY/results/result hecatomb_out/RESULTS/MMSEQS_NT_PRIMARY/results/firsthit --extract-lines 1

**Comment by beardymcjohnface** [comment]
I forgot to mention this in today's meeting; I do occasionally get this sort of error and I don't know how to troubleshoot these MMSeqs issues. Sometimes rerunning works, sometimes deleting the query DBs and rerunning works. I'm hoping newer versions of MMSeqs have helped with stability.
