### ISSUE TITLE
Missing new line in contigAnnotations.tsv

### ISSUE THREAD

**Issue by mihinduk** [shandley/hecatomb#75]
Hi Mike, 
In the contigAnnotations.tsv that we downloaded for the combined run, there is no newline between the end of the header and the start of the data.

contigID	evalue	pident	fident	nident	mismatch	qcov	tcov	qstart	qend	qlen	tstart	tend	tlen	alnlen	bits	target	kingdomphylum	class	order	family	genus	**speciescontig_135513**	0.000E+00	96.400	0.964	0	30	0.825	0.005	178	1009	1009	1685	2520	165175	836	1355	tid|2292287|NZ_QSCM01000008.1	Bacteria	Firmicutes	Clostridia	Clostridiales	Lachnospiraceae	Blautia	Blautia sp. OF03-15BH

Kathie

**Comment by beardymcjohnface** [comment]
Thanks Kathie, I did notice this and I tested a fix but it's not in the current release; I'll have to patch it asap.
