### ISSUE TITLE
fastp not building

### ISSUE THREAD

**Issue by beardymcjohnface** [shandley/hecatomb#76]
running into issue with fastp not building with conda strict channel priorities on NCI.
work around is to unset strict, build fastp, and reset strict.

**Comment by alanorth** [comment]
We are hitting this while running the hecatomb tests. So how do we do that? I tried this:

```console
$ hecatomb run --test --threads 8
...
CreateCondaEnvironmentException:
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please configure strict priorities by executing 'conda config --set channel_priority strict'.  
$ conda config --set channel_priority strict
$ hecatomb run --test --threads 8
...
Output:
Encountered problems while solving:
  - package fastp-0.23.2-hd36eab0_1 requires libdeflate >=1.9,<1.10.0a0, but none of the providers can be installed
$ conda config --set channel_priority false
$ hecatomb run --test --threads 8
...
CreateCondaEnvironmentException:
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please configure strict priorities by executing 'conda config --set channel_priority strict'.  
```

**Comment by beardymcjohnface** [comment]
Hi Alan,
Find your conda installation folder with 
```
which hecatomb
```
it should come back with something like `~/miniconda3/envs/hecatomb/bin/hecatomb`, so the hecatomb env would be `~/miniconda3/envs/hecatomb`, and the conda environments for the pipeline are in `snakemake/workflow/conda/` in the env directory (so `~/miniconda3/envs/hecatomb/snakemake/workflow/conda/` for me). 

Find the fastp env directory with:
```
grep fastp ~/miniconda3/envs/hecatomb/snakemake/workflow/conda/*.yaml
```
for me it was `~/miniconda3/envs/hecatomb/snakemake/workflow/conda/c9bd6a8dd6dec26c660f249cd191d4e3.yaml` so I would activate the fastp env like so:
```
conda activate ~/miniconda3/envs/hecatomb/snakemake/workflow/conda/c9bd6a8dd6dec26c660f249cd191d4e3/
```
then install fastp with conda. It might just be a build issue for that specific version of fastp so you could try building an older version or a specific build:
```
mamba install fastp
# or 
mamba install fastp=0.23.2=hb7a2d85_2
# or
mamba install fastp=0.23.1
# test it
fastp --help
```
Then deactivate, reactive your hecatomb env if needed and try rerunning the test dataset.

**Comment by beardymcjohnface** [comment]
I just tried this and I think this might be a much more robust way to go:
```yaml
name: fastp
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::fastp=0.23.2
  - conda-forge::_libgcc_mutex>=0.1
  - conda-forge::_openmp_mutex>=4.5
  - conda-forge::isa-l>=2.30.0
  - conda-forge::libdeflate>=1.10
  - conda-forge::libgcc-ng>=12.1.0
  - conda-forge::libgomp>=12.1.0
  - conda-forge::libstdcxx-ng>=12.1.0
```

**Comment by linsalrob** [comment]
I think we should post a [bioconda issue](https://github.com/bioconda/bioconda-recipes/issues) to remove the out of date version of the dependencies. They should not be in both bioconda and conda-forge.

**Comment by beardymcjohnface** [comment]
I'm hoping this is now fixed, but please reopen or open a new issue if you're still having problems with this.
