### ISSUE TITLE
Check for the presence of an environment variable for location of databases

### ISSUE THREAD

**Issue by linsalrob** [shandley/hecatomb#80]
Can we please define an environmental variable `HECATOMB_DB` that is checked for first?

If set, we should use this as the location of the databases and die with an appropriate error if the databases are not present in this location. 

This would allow multiple users to access the database from a common location (this is similar to `$KRAKEN2_DEFAULT_DB` and `$SUPERFOCUS_DB`)

**Comment by beardymcjohnface** [comment]
Hecatomb will look for DB location in the following order:

config > environment variable `HECATOMB_DB` > default location
