### ISSUE TITLE
readthedocs viral ecology R tutorial error fix

### ISSUE THREAD

**Issue by RyCrobe** [shandley/hecatomb#82]
Hey hecatombers,

This is just a nudge about a common error you get when you run an nmds with the new version of vegan.

If you do 
> data.scores = as.data.frame(scores(nmds)) 

you get an error about arguments implying different numbers of rows

instead you have to do 
>data.scores = as.data.frame(scores(nmds)$sites)

and that worked fine.

Thanks,
Ryan

**Comment by beardymcjohnface** [comment]
fixed, thanks Ryan!
